import { db } from "./db";
import { templates } from "@shared/schema";

const heroImages = {
  corporate: [
    "photo-1486406146926-c627a92ad1ab", "photo-1497366216548-37526070297c", "photo-1552664730-d307ca884978",
    "photo-1556761175-b413da4baf72", "photo-1507003211169-0a1dd7228f2d", "photo-1560179707-f14e90ef3623",
    "photo-1542744173-8e7e53415bb0", "photo-1454165804606-c3d57bc86b40", "photo-1521737604893-d14cc237f11d",
    "photo-1553877522-43269d4ea984", "photo-1600880292203-757bb62b4baf", "photo-1504384308090-c894fdcc538d",
    "photo-1573497620053-ea5300f94f21", "photo-1519389950473-47ba0277781c", "photo-1557804506-669a67965ba0",
    "photo-1460925895917-afdab827c52f", "photo-1551434678-e076c223a692", "photo-1519494026892-80bbd2d6fd0d",
    "photo-1560518883-ce09059eeffa", "photo-1541643600914-78b084683601",
  ],
  exhibition: [
    "photo-1540575467063-178a50c2df87", "photo-1505236858219-8359eb29e329", "photo-1531058020387-3be344556be6",
    "photo-1492684223f8-5e88b6194e3c", "photo-1514525253161-7a46d19cd819", "photo-1501281668745-f7f57925c3b4",
    "photo-1478720568477-152d9b164e26", "photo-1506157786151-b8491531f063", "photo-1429962714451-bb934ecdc4ec",
    "photo-1459749411175-04bf5292ceea", "photo-1511578314322-379afb476865", "photo-1533174072545-7a4b6ad7a6c3",
    "photo-1470229722913-7c0e2dbbafd3", "photo-1492684223f8-5e88b6194e3c", "photo-1560523159-4a9692d222ef",
    "photo-1587825140708-dfaf18c4b4af", "photo-1559519529-0936de16e0fb", "photo-1508997449629-303059a039c0",
    "photo-1547826039-bfc35e0f1ea8", "photo-1516450360452-9312f5e86fc7",
  ],
  restaurant: [
    "photo-1517248135467-4c7edcad34c4", "photo-1554118811-1e0d58224f24", "photo-1414235077428-338989a2e8c0",
    "photo-1504674900247-0877df9cc836", "photo-1555396273-367ea4eb4db5", "photo-1424847651672-bf20a4b0982b",
    "photo-1559339352-11d035aa65de", "photo-1466978913421-dad2ebd01d17", "photo-1528605248644-14dd04022da1",
    "photo-1537047902294-62a40c20a6ae", "photo-1544025162-d76694265947", "photo-1571091718767-18b5b1457add",
    "photo-1565299624946-b28f40a0ae38", "photo-1482049016688-2d3e1b311543", "photo-1476224203421-9ac39bcb3327",
    "photo-1551218808-94e220e084d2", "photo-1559847844-5315695dadae", "photo-1590846406792-0adc7f938f1d",
    "photo-1568901346375-23c9450c58cd", "photo-1506354666786-959d6d497f1a",
  ],
  startup: [
    "photo-1522071820081-009f0129c71c", "photo-1451187580459-43490279c0fa", "photo-1519389950473-47ba0277781c",
    "photo-1535378917042-10a22c95931a", "photo-1504384308090-c894fdcc538d", "photo-1553877522-43269d4ea984",
    "photo-1559136555-9303baea8ebd", "photo-1542744094-24638eff58bb", "photo-1531297484001-80022131f5a1",
    "photo-1517694712202-14dd9538aa97", "photo-1498050108023-c5249f4df085", "photo-1461749280684-dccba630e2f6",
    "photo-1504639725590-34d0984388bd", "photo-1518770660439-4636190af475", "photo-1550751827-4bd374c3f58b",
    "photo-1558494949-ef010cbdcc31", "photo-1555255707-c07966088b7b", "photo-1520607162513-77705c0f0d4a",
    "photo-1551288049-bebda4e38f71", "photo-1581091226825-a6a2a5aee158",
  ],
  portfolio: [
    "photo-1558618666-fcd25c85f82e", "photo-1513542789411-b6a5d4f31634", "photo-1445205170230-053b83016050",
    "photo-1523726491678-bf852e717f6a", "photo-1460661419907-4a21e1eae4f0", "photo-1502691876148-a84978e59af8",
    "photo-1534312527009-56c7016453e6", "photo-1561070791-2526d30994b5", "photo-1507003211169-0a1dd7228f2d",
    "photo-1452587925148-ce544e77e70d", "photo-1468276311594-df7cb65d8df6", "photo-1541701494587-cb58502866ab",
    "photo-1504198266287-1659872e6590", "photo-1526040652367-ac003a0475fe", "photo-1519681393784-d120267933ba",
    "photo-1503023345310-bd7c1de61c7d", "photo-1500462918059-b1a0cb512f1d", "photo-1493238792000-8113da705763",
    "photo-1506905925346-21bda4d32df4", "photo-1518098268026-4e89f1a2cd8e",
  ],
  landing: [
    "photo-1460925895917-afdab827c52f", "photo-1551434678-e076c223a692", "photo-1559136555-9303baea8ebd",
    "photo-1504384308090-c894fdcc538d", "photo-1553877522-43269d4ea984", "photo-1519389950473-47ba0277781c",
    "photo-1551288049-bebda4e38f71", "photo-1542744173-8e7e53415bb0", "photo-1600880292203-757bb62b4baf",
    "photo-1573497620053-ea5300f94f21", "photo-1557804506-669a67965ba0", "photo-1499951360447-b19be8fe80f5",
    "photo-1517694712202-14dd9538aa97", "photo-1535378917042-10a22c95931a", "photo-1498050108023-c5249f4df085",
    "photo-1504639725590-34d0984388bd", "photo-1558494949-ef010cbdcc31", "photo-1520607162513-77705c0f0d4a",
    "photo-1555255707-c07966088b7b", "photo-1581091226825-a6a2a5aee158",
  ],
  ecommerce: [
    "photo-1441986300917-64674bd600d8", "photo-1558618666-fcd25c85f82e", "photo-1541643600914-78b084683601",
    "photo-1556742049-0cfed4f6a45d", "photo-1472851294608-062f824d29cc", "photo-1483985988355-763728e1935b",
    "photo-1445205170230-053b83016050", "photo-1607082348824-0a96f2a4b9da", "photo-1523275335684-37898b6baf30",
    "photo-1526170375885-4d8ecf77b99f", "photo-1560343090-f0409e92791a", "photo-1542291026-7eec264c27ff",
    "photo-1549298916-b41d501d3772", "photo-1553062407-98eeb64c6a62", "photo-1505740420928-5e560c06d30e",
    "photo-1596462502278-27bfdc403348", "photo-1491553895911-0055eca6402d", "photo-1584917865442-de89df76afd3",
    "photo-1524592094714-0f0654e20314", "photo-1485462537746-965f33f7f6a7",
  ],
};

const gradients = [
  "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
  "linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)",
  "linear-gradient(135deg, #064e3b 0%, #065f46 100%)",
  "linear-gradient(135deg, #7c2d12 0%, #9a3412 100%)",
  "linear-gradient(135deg, #1e3a5f 0%, #2c5282 100%)",
  "linear-gradient(135deg, #3b0764 0%, #581c87 100%)",
  "linear-gradient(135deg, #0c4a6e 0%, #075985 100%)",
  "linear-gradient(135deg, #134e4a 0%, #115e59 100%)",
  "linear-gradient(135deg, #4c1d95 0%, #6d28d9 100%)",
  "linear-gradient(135deg, #831843 0%, #9d174d 100%)",
  "linear-gradient(135deg, #0a0a0a 0%, #171717 100%)",
  "linear-gradient(135deg, #78350f 0%, #92400e 100%)",
  "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
  "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
  "linear-gradient(135deg, #dc2626 0%, #ea580c 100%)",
  "linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)",
  "linear-gradient(135deg, #059669 0%, #0d9488 100%)",
  "linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)",
  "linear-gradient(135deg, #d97706 0%, #b45309 100%)",
  "linear-gradient(135deg, #1c1917 0%, #292524 100%)",
];

const accentColors = [
  "#3b82f6", "#8b5cf6", "#06b6d4", "#10b981", "#f59e0b",
  "#ec4899", "#ef4444", "#6366f1", "#14b8a6", "#d4a843",
  "#f0c96e", "#a78bfa", "#22d3ee", "#34d399", "#fb923c",
  "#f472b6", "#c084fc", "#2dd4bf", "#fbbf24", "#f87171",
];

interface TemplateConfig {
  names: { en: string; ar: string }[];
  descriptions: { en: string; ar: string }[];
  heroTitles: string[];
  heroSubtitles: string[];
  ctaTexts: string[];
  featureNames: string[][];
}

const categoryConfigs: Record<string, TemplateConfig> = {
  corporate: {
    names: [
      { en: "Corporate Pro", ar: "شركات احترافي" },
      { en: "Corporate Elite", ar: "شركات النخبة" },
      { en: "Business Hub", ar: "مركز الأعمال" },
      { en: "Enterprise Suite", ar: "حلول المؤسسات" },
      { en: "Consultant Pro", ar: "مستشار محترف" },
      { en: "Marketing Agency", ar: "وكالة تسويق" },
      { en: "Medical Clinic", ar: "عيادة طبية" },
      { en: "Real Estate Luxury", ar: "عقارات فاخرة" },
      { en: "Law Firm", ar: "مكتب محاماة" },
      { en: "Finance Group", ar: "مجموعة مالية" },
      { en: "Tech Corp", ar: "شركة تقنية" },
      { en: "Construction Co", ar: "شركة مقاولات" },
      { en: "Insurance Pro", ar: "تأمين محترف" },
      { en: "Logistics Hub", ar: "مركز لوجستي" },
      { en: "HR Solutions", ar: "حلول الموارد البشرية" },
      { en: "Accounting Firm", ar: "مكتب محاسبة" },
      { en: "Dental Care", ar: "عيادة أسنان" },
      { en: "Architecture Studio", ar: "استوديو معماري" },
      { en: "Trading Company", ar: "شركة تجارة" },
      { en: "Investment Group", ar: "مجموعة استثمار" },
    ],
    descriptions: [
      { en: "Professional corporate website template", ar: "قالب موقع شركات احترافي" },
      { en: "Premium business template with modern design", ar: "قالب أعمال فاخر بتصميم حديث" },
      { en: "Clean corporate template for enterprises", ar: "قالب شركات نظيف للمؤسسات" },
      { en: "Enterprise-grade website template", ar: "قالب موقع بمستوى المؤسسات" },
      { en: "Advisory services professional template", ar: "قالب خدمات استشارية احترافي" },
      { en: "Bold marketing agency template", ar: "قالب وكالة تسويق جريء" },
      { en: "Trust-building medical template", ar: "قالب طبي يبني الثقة" },
      { en: "Luxury real estate showcase", ar: "عرض عقارات فاخرة" },
      { en: "Elegant law firm template", ar: "قالب مكتب محاماة أنيق" },
      { en: "Financial services template", ar: "قالب خدمات مالية" },
      { en: "Modern tech company template", ar: "قالب شركة تقنية حديث" },
      { en: "Construction company template", ar: "قالب شركة مقاولات" },
      { en: "Insurance services template", ar: "قالب خدمات تأمين" },
      { en: "Logistics and shipping template", ar: "قالب لوجستيات وشحن" },
      { en: "HR solutions template", ar: "قالب حلول موارد بشرية" },
      { en: "Accounting firm template", ar: "قالب مكتب محاسبة" },
      { en: "Dental clinic template", ar: "قالب عيادة أسنان" },
      { en: "Architecture studio template", ar: "قالب استوديو معماري" },
      { en: "Trading company template", ar: "قالب شركة تجارة" },
      { en: "Investment group template", ar: "قالب مجموعة استثمار" },
    ],
    heroTitles: [
      "حلول أعمال متكاملة", "النخبة في عالم الأعمال", "شريكك نحو النجاح",
      "حلول مؤسسية متقدمة", "استشارات احترافية", "نصنع علامتك التجارية",
      "صحتك أولويتنا", "عقارات فاخرة", "العدالة في خدمتك",
      "حلول مالية ذكية", "ابتكار بلا حدود", "نبني المستقبل",
      "تأمين يحميك", "نوصل العالم", "نهتم بفريقك",
      "أرقام تتحدث", "ابتسامة مشرقة", "تصميم يلهم",
      "تجارة عالمية", "استثمار ذكي",
    ],
    heroSubtitles: [
      "نقدم حلول أعمال مبتكرة تدعم نمو شركتك وتحقق أهدافك",
      "خبرة تمتد لأكثر من عقد في خدمة كبرى الشركات والمؤسسات",
      "نساعدك في بناء مستقبل أعمالك بثقة واحترافية عالية",
      "حلول تقنية وإدارية متكاملة للمؤسسات الكبرى",
      "فريق من الخبراء المتخصصين في تطوير الأعمال",
      "نصمم حملات تسويقية تحقق نتائج استثنائية",
      "فريق طبي متخصص يقدم أفضل الخدمات الصحية",
      "عقارات مميزة في أفضل المواقع بأسعار تنافسية",
      "محامون متخصصون يحمون حقوقك بكل احترافية",
      "خبراء ماليون يساعدونك في اتخاذ القرارات الصحيحة",
      "نطور حلول تقنية مبتكرة تغير قواعد اللعبة",
      "نبني المشاريع بأعلى معايير الجودة والسلامة",
      "برامج تأمين شاملة تحمي ما يهمك",
      "حلول لوجستية متكاملة تصل العالم ببعضه",
      "نساعد في بناء فرق عمل قوية وفعالة",
      "خدمات محاسبية دقيقة وشفافة لأعمالك",
      "نرسم ابتسامتك بأحدث تقنيات طب الأسنان",
      "تصاميم معمارية تجمع بين الجمال والوظيفة",
      "شبكة تجارية واسعة تربطك بالأسواق العالمية",
      "فرص استثمارية ذكية تنمي ثروتك بأمان",
    ],
    ctaTexts: [
      "ابدأ الآن", "تواصل معنا", "احجز استشارة", "اطلب عرض سعر",
      "اكتشف المزيد", "انضم إلينا", "احجز موعدك", "شاهد المشاريع",
      "استشر محامينا", "ابدأ الاستثمار", "جرب مجاناً", "تواصل الآن",
      "احصل على تقييم", "تتبع شحنتك", "قدم طلبك", "احسب ضريبتك",
      "احجز فحصك", "شاهد أعمالنا", "ابدأ التداول", "استثمر الآن",
    ],
    featureNames: [
      ["الاستشارات", "التخطيط", "الابتكار"],
      ["التصميم", "التطوير", "الدعم"],
      ["التسويق", "التحليل", "النتائج"],
    ],
  },
  exhibition: {
    names: [
      { en: "Exhibition Showcase", ar: "عرض المعارض" },
      { en: "Luxury Exhibition", ar: "معرض فاخر" },
      { en: "Art Gallery", ar: "معرض فني" },
      { en: "Museum Modern", ar: "متحف حديث" },
      { en: "Cultural Festival", ar: "مهرجان ثقافي" },
      { en: "Fashion Show", ar: "عرض أزياء" },
      { en: "Tech Expo", ar: "معرض تقني" },
      { en: "Book Fair", ar: "معرض كتاب" },
      { en: "Auto Show", ar: "معرض سيارات" },
      { en: "Food Festival", ar: "مهرجان الطعام" },
      { en: "Music Concert", ar: "حفل موسيقي" },
      { en: "Photo Exhibition", ar: "معرض تصوير" },
      { en: "Design Week", ar: "أسبوع التصميم" },
      { en: "Science Fair", ar: "معرض علمي" },
      { en: "Film Festival", ar: "مهرجان سينمائي" },
      { en: "Sports Event", ar: "فعالية رياضية" },
      { en: "Wedding Expo", ar: "معرض أعراس" },
      { en: "Startup Summit", ar: "قمة الشركات الناشئة" },
      { en: "Health Conference", ar: "مؤتمر صحي" },
      { en: "Education Forum", ar: "منتدى تعليمي" },
    ],
    descriptions: [
      { en: "Elegant exhibition template", ar: "قالب معرض أنيق" },
      { en: "Luxury dark exhibition with gold accents", ar: "معرض فاخر داكن بلمسات ذهبية" },
      { en: "Modern art gallery template", ar: "قالب معرض فني حديث" },
      { en: "Contemporary museum template", ar: "قالب متحف معاصر" },
      { en: "Cultural festival template", ar: "قالب مهرجان ثقافي" },
      { en: "Fashion show event template", ar: "قالب فعالية عرض أزياء" },
      { en: "Technology expo template", ar: "قالب معرض تقنية" },
      { en: "Book fair and literary event", ar: "قالب معرض كتاب وفعاليات أدبية" },
      { en: "Automotive showcase template", ar: "قالب عرض سيارات" },
      { en: "Food and culinary festival", ar: "قالب مهرجان طعام وطهي" },
      { en: "Music concert event template", ar: "قالب فعالية حفل موسيقي" },
      { en: "Photography exhibition template", ar: "قالب معرض تصوير فوتوغرافي" },
      { en: "Design week event template", ar: "قالب فعالية أسبوع التصميم" },
      { en: "Science and innovation fair", ar: "قالب معرض علوم وابتكار" },
      { en: "Film festival template", ar: "قالب مهرجان سينمائي" },
      { en: "Sports event template", ar: "قالب فعالية رياضية" },
      { en: "Wedding expo template", ar: "قالب معرض أعراس وزفاف" },
      { en: "Startup summit template", ar: "قالب قمة شركات ناشئة" },
      { en: "Health conference template", ar: "قالب مؤتمر صحي" },
      { en: "Education forum template", ar: "قالب منتدى تعليمي" },
    ],
    heroTitles: [
      "معرض الإبداع ٢٠٢٦", "أرتيزان الدولي", "فنون بلا حدود",
      "المتحف الحديث", "مهرجان الثقافة العربية", "أزياء الموسم",
      "معرض التقنية", "معرض الكتاب الدولي", "معرض السيارات الفاخرة",
      "مهرجان المذاقات", "ليالي الطرب", "عدسة وصورة",
      "أسبوع التصميم العربي", "مستقبل العلوم", "المهرجان السينمائي",
      "ملتقى الرياضة", "حلم الزفاف", "قمة الابتكار",
      "ملتقى الصحة", "أفق المعرفة",
    ],
    heroSubtitles: [
      "اكتشف الإبداع والابتكار في أكبر معرض فني في المنطقة",
      "معرض فني دولي يجمع أرقى الأعمال الإبداعية من حول العالم",
      "فنون من مختلف الثقافات تجتمع في مكان واحد",
      "رحلة عبر الزمن في أحدث المتاحف التفاعلية",
      "احتفال بالتراث والثقافة العربية الأصيلة",
      "أحدث صيحات الموضة من أشهر المصممين العرب",
      "أحدث التقنيات والابتكارات تحت سقف واحد",
      "آلاف العناوين من أفضل دور النشر العربية والعالمية",
      "أفخم السيارات وأحدث الموديلات في مكان واحد",
      "تذوق نكهات من مختلف أنحاء العالم العربي",
      "أمسيات موسيقية مع أشهر الفنانين العرب",
      "معرض للتصوير الفوتوغرافي يروي قصصاً بالصور",
      "أبرز المصممين العرب يعرضون أحدث إبداعاتهم",
      "اكتشافات علمية وابتكارات تغير المستقبل",
      "أفضل الأفلام العربية والعالمية على شاشة واحدة",
      "أبطال الرياضة يجتمعون في أكبر ملتقى رياضي",
      "كل ما تحتاجه لحفل زفاف أحلامك في مكان واحد",
      "ملتقى رواد الأعمال والمستثمرين",
      "أحدث الاكتشافات الصحية والطبية",
      "ملتقى تعليمي يجمع أفضل الخبراء والمتحدثين",
    ],
    ctaTexts: [
      "احجز تذكرتك", "سجل الآن", "اكتشف المزيد", "شاهد البرنامج",
      "انضم إلينا", "احصل على تذكرتك", "سجل مبكراً", "زر المعرض",
      "احجز مقعدك", "تذوق النكهات", "احجز تذكرتك", "شاهد المعرض",
      "سجل الآن", "اكتشف المستقبل", "شاهد الأفلام", "انضم للملتقى",
      "خطط لزفافك", "سجل شركتك", "احجز مكانك", "سجل حضورك",
    ],
    featureNames: [
      ["فنانون عالميون", "ورش عمل", "تجارب حية"],
      ["معارض متعددة", "فعاليات تفاعلية", "جوائز مميزة"],
      ["ضيوف مميزون", "عروض حصرية", "تذاكر VIP"],
    ],
  },
  restaurant: {
    names: [
      { en: "Restaurant Delight", ar: "مطعم فاخر" },
      { en: "Cafe Modern", ar: "مقهى حديث" },
      { en: "Sushi Master", ar: "سوشي ماستر" },
      { en: "Arabian Nights", ar: "ليالي عربية" },
      { en: "Pizza Palace", ar: "قصر البيتزا" },
      { en: "Steak House", ar: "بيت اللحوم" },
      { en: "Bakery Fresh", ar: "مخبز طازج" },
      { en: "Seafood Bay", ar: "خليج المأكولات البحرية" },
      { en: "Ice Cream Lab", ar: "مختبر الآيسكريم" },
      { en: "Burger Joint", ar: "بيت البرغر" },
      { en: "Tea House", ar: "بيت الشاي" },
      { en: "Juice Bar", ar: "بار العصائر" },
      { en: "Food Truck", ar: "عربة الطعام" },
      { en: "Fine Dining", ar: "مطعم راقي" },
      { en: "Fast Grill", ar: "شواية سريعة" },
      { en: "Noodle Bar", ar: "بار المعكرونة" },
      { en: "Dessert House", ar: "بيت الحلويات" },
      { en: "BBQ Smokehouse", ar: "بيت المشاوي" },
      { en: "Vegan Kitchen", ar: "مطبخ نباتي" },
      { en: "Brunch Spot", ar: "ركن الفطور" },
    ],
    descriptions: [
      { en: "Warm restaurant template", ar: "قالب مطعم دافئ وجذاب" },
      { en: "Modern cafe template", ar: "قالب مقهى حديث" },
      { en: "Japanese restaurant template", ar: "قالب مطعم ياباني" },
      { en: "Arabian cuisine template", ar: "قالب مطبخ عربي أصيل" },
      { en: "Italian pizzeria template", ar: "قالب بيتزا إيطالية" },
      { en: "Premium steakhouse template", ar: "قالب مطعم لحوم فاخر" },
      { en: "Fresh bakery template", ar: "قالب مخبز طازج" },
      { en: "Seafood restaurant template", ar: "قالب مطعم مأكولات بحرية" },
      { en: "Ice cream shop template", ar: "قالب محل آيسكريم" },
      { en: "Burger restaurant template", ar: "قالب مطعم برغر" },
      { en: "Tea house template", ar: "قالب بيت شاي" },
      { en: "Juice bar template", ar: "قالب بار عصائر" },
      { en: "Food truck template", ar: "قالب عربة طعام" },
      { en: "Fine dining template", ar: "قالب مطعم راقي" },
      { en: "Fast grill template", ar: "قالب شواية سريعة" },
      { en: "Noodle bar template", ar: "قالب بار معكرونة" },
      { en: "Dessert house template", ar: "قالب بيت حلويات" },
      { en: "BBQ smokehouse template", ar: "قالب بيت مشاوي" },
      { en: "Vegan kitchen template", ar: "قالب مطبخ نباتي" },
      { en: "Brunch spot template", ar: "قالب ركن فطور" },
    ],
    heroTitles: [
      "لا ميزون", "مقهى ومحمصة", "سوشي ماستر",
      "ليالي عربية", "قصر البيتزا", "بيت اللحوم المميز",
      "مخبز طازج يومياً", "أطيب المأكولات البحرية", "مختبر النكهات المجمدة",
      "أفضل برغر في المدينة", "بيت الشاي الأصيل", "عصائر طازجة طبيعية",
      "نكهات على العجلات", "تجربة طعام لا تُنسى", "شواية نار مباشرة",
      "نودلز طازجة يومياً", "حلويات تذوب في الفم", "مشاوي على الفحم",
      "مطبخ نباتي صحي", "فطور كل يوم",
    ],
    heroSubtitles: [
      "تجربة طعام فاخرة في أجواء ساحرة تأخذك في رحلة من النكهات",
      "قهوة مختصة محمصة بعناية مع أجمل المعجنات الطازجة يومياً",
      "أشهى أطباق السوشي الطازج محضرة بأيدي أمهر الطهاة",
      "مأكولات عربية أصيلة بنكهة تراثية في أجواء شرقية ساحرة",
      "بيتزا إيطالية أصلية من فرن الحطب مع أجود المكونات",
      "أفخر قطع اللحوم المشوية على الفحم بوصفات حصرية",
      "خبز طازج ومعجنات محضرة يومياً بأفضل المكونات الطبيعية",
      "أطيب المأكولات البحرية الطازجة من البحر إلى طبقك مباشرة",
      "نكهات آيسكريم مبتكرة تُحضر أمامك بتقنيات فريدة",
      "برغر لحم طازج ١٠٠٪ مع وصفات صلصات سرية مميزة",
      "أنواع الشاي الفاخرة من حول العالم في أجواء هادئة",
      "عصائر طازجة ومشروبات صحية محضرة من أفضل الفواكه",
      "طعام شارع مميز بنكهات عالمية متنوعة",
      "تجربة طعام فاخرة تجمع بين الإبداع والنكهات الراقية",
      "لحوم مشوية على نار مباشرة بتتبيلات خاصة ومميزة",
      "نودلز طازجة محضرة يومياً بوصفات آسيوية أصيلة",
      "حلويات شرقية وغربية محضرة بأيدي أمهر الحلوانيين",
      "مشاوي على الفحم مع أطيب المقبلات والسلطات",
      "أطباق نباتية صحية ولذيذة تثبت أن الصحي ممتع",
      "فطور متنوع يبدأ يومك بابتسامة ونشاط",
    ],
    ctaTexts: [
      "احجز طاولتك", "اطلب الآن", "شاهد القائمة", "اطلب توصيل",
      "احجز مقعدك", "جرب قائمتنا", "اطلب كيكتك", "اطلب طازج",
      "اختر نكهتك", "اطلب برغرك", "احجز جلستك", "اطلب عصيرك",
      "اطلب من العربة", "احجز تجربتك", "اطلب شوايتك", "اختر طبقك",
      "اطلب حلوياتك", "احجز شوايتك", "اطلب وجبتك", "احجز فطورك",
    ],
    featureNames: [
      ["المقبلات", "الأطباق الرئيسية", "الحلويات"],
      ["قهوة مختصة", "معجنات طازجة", "أجواء مريحة"],
      ["مكونات طازجة", "وصفات حصرية", "خدمة مميزة"],
    ],
  },
  startup: {
    names: [
      { en: "Startup Launch", ar: "إطلاق شركة ناشئة" },
      { en: "Tech Innovator", ar: "المبتكر التقني" },
      { en: "AI Platform", ar: "منصة ذكاء اصطناعي" },
      { en: "Fintech Pro", ar: "فينتك احترافي" },
      { en: "EdTech Learn", ar: "تعليم تقني" },
      { en: "HealthTech", ar: "تقنية صحية" },
      { en: "Cloud Suite", ar: "حلول سحابية" },
      { en: "Cyber Shield", ar: "درع الأمان" },
      { en: "Data Analytics", ar: "تحليل البيانات" },
      { en: "IoT Connect", ar: "إنترنت الأشياء" },
      { en: "Blockchain Hub", ar: "مركز البلوكتشين" },
      { en: "AR Vision", ar: "رؤية الواقع المعزز" },
      { en: "Dev Tools", ar: "أدوات المطورين" },
      { en: "API Gateway", ar: "بوابة الربط" },
      { en: "Smart City", ar: "مدينة ذكية" },
      { en: "Green Tech", ar: "تقنية خضراء" },
      { en: "Robo Advisor", ar: "مستشار آلي" },
      { en: "EduBot", ar: "روبوت تعليمي" },
      { en: "LogiTech", ar: "لوجيتك" },
      { en: "MarTech Pro", ar: "تسويق تقني" },
    ],
    descriptions: [
      { en: "Bold startup template", ar: "قالب شركة ناشئة جريء" },
      { en: "Futuristic tech template", ar: "قالب تقنية مستقبلي" },
      { en: "AI platform landing page", ar: "صفحة منصة ذكاء اصطناعي" },
      { en: "Financial technology template", ar: "قالب تقنية مالية" },
      { en: "Education technology template", ar: "قالب تقنية تعليمية" },
      { en: "Health technology template", ar: "قالب تقنية صحية" },
      { en: "Cloud services template", ar: "قالب خدمات سحابية" },
      { en: "Cybersecurity template", ar: "قالب أمن سيبراني" },
      { en: "Data analytics platform", ar: "قالب منصة تحليل بيانات" },
      { en: "IoT solutions template", ar: "قالب حلول إنترنت الأشياء" },
      { en: "Blockchain technology template", ar: "قالب تقنية البلوكتشين" },
      { en: "Augmented reality template", ar: "قالب واقع معزز" },
      { en: "Developer tools template", ar: "قالب أدوات مطورين" },
      { en: "API management template", ar: "قالب إدارة واجهات برمجية" },
      { en: "Smart city solutions", ar: "قالب حلول المدن الذكية" },
      { en: "Green technology template", ar: "قالب تقنية خضراء" },
      { en: "Robo advisory template", ar: "قالب مستشار آلي" },
      { en: "Education robot template", ar: "قالب روبوت تعليمي" },
      { en: "Logistics tech template", ar: "قالب تقنية لوجستية" },
      { en: "Marketing tech template", ar: "قالب تقنية تسويقية" },
    ],
    heroTitles: [
      "أطلق رؤيتك", "نيكسس الذكي", "مستقبل الذكاء الاصطناعي",
      "مستقبل المال", "تعلّم بذكاء", "صحتك رقمياً",
      "سحابة بلا حدود", "أمانك الرقمي", "بياناتك تتحدث",
      "كل شيء متصل", "ثورة البلوكتشين", "عالم جديد",
      "أدوات المستقبل", "اربط كل شيء", "مدينة المستقبل",
      "تقنية خضراء", "مستشارك الآلي", "معلم المستقبل",
      "لوجستيات ذكية", "تسويق بالبيانات",
    ],
    heroSubtitles: [
      "المنصة التي تنمو معك من الفكرة إلى النجاح العالمي",
      "منصة ذكاء اصطناعي من الجيل القادم تغير قواعد اللعبة",
      "حلول ذكاء اصطناعي متقدمة تحول أعمالك بالكامل",
      "حلول مالية رقمية آمنة وسريعة لعالم بلا حدود",
      "منصة تعليمية تفاعلية تجعل التعلم ممتعاً وفعالاً",
      "حلول صحية رقمية تربط المرضى بأفضل الأطباء",
      "بنية سحابية تحتية موثوقة تدعم نمو أعمالك",
      "حلول أمان سيبراني متقدمة تحمي بياناتك وأعمالك",
      "حول بياناتك إلى قرارات ذكية مع تحليلات متقدمة",
      "اربط أجهزتك وأنظمتك في شبكة ذكية واحدة",
      "حلول بلوكتشين آمنة وشفافة للمعاملات الرقمية",
      "تجارب واقع معزز تغير طريقة تفاعلك مع العالم",
      "أدوات تطوير قوية تسرع عملية البناء والنشر",
      "إدارة واجهات برمجية سلسة وآمنة لتطبيقاتك",
      "حلول ذكية تجعل المدن أكثر كفاءة واستدامة",
      "تقنيات مستدامة تحمي البيئة وتنمي الأعمال",
      "استشارات مالية آلية ذكية تنمي استثماراتك",
      "روبوتات تعليمية تفاعلية تجعل التعلم مغامرة",
      "حلول لوجستية ذكية تحسن سلسلة التوريد",
      "أدوات تسويقية مدعومة بالذكاء الاصطناعي",
    ],
    ctaTexts: [
      "ابدأ مجاناً", "جرب الآن", "سجل مبكراً", "ابدأ تجربتك",
      "انضم للقائمة", "سجل الآن", "ابدأ بناء", "احمِ بياناتك",
      "حلل بياناتك", "اربط أجهزتك", "ابدأ الآن", "جرب التجربة",
      "ابدأ البناء", "اربط تطبيقاتك", "اكتشف الحلول", "ابدأ أخضر",
      "ابدأ الاستثمار", "جرب الروبوت", "حسّن عملياتك", "عزز تسويقك",
    ],
    featureNames: [
      ["سرعة ١٠x", "وقت تشغيل ٩٩.٩٪", "دعم ٢٤/٧"],
      ["ذكاء اصطناعي", "تعلم آلي", "أتمتة"],
      ["أمان عالي", "سرعة فائقة", "سهولة الاستخدام"],
    ],
  },
  portfolio: {
    names: [
      { en: "Creative Portfolio", ar: "معرض إبداعي" },
      { en: "Minimal Portfolio", ar: "معرض بسيط" },
      { en: "Photography Pro", ar: "تصوير احترافي" },
      { en: "Design Studio", ar: "استوديو تصميم" },
      { en: "Filmmaker", ar: "صانع أفلام" },
      { en: "Illustrator", ar: "رسام محترف" },
      { en: "Architect Folio", ar: "معرض معماري" },
      { en: "Fashion Designer", ar: "مصمم أزياء" },
      { en: "Music Artist", ar: "فنان موسيقي" },
      { en: "Freelancer", ar: "مستقل محترف" },
      { en: "Writer Portfolio", ar: "معرض كاتب" },
      { en: "UX Designer", ar: "مصمم تجربة" },
      { en: "Brand Identity", ar: "هوية علامة تجارية" },
      { en: "Motion Designer", ar: "مصمم حركة" },
      { en: "3D Artist", ar: "فنان ثلاثي الأبعاد" },
      { en: "Interior Design", ar: "تصميم داخلي" },
      { en: "Calligrapher", ar: "خطاط محترف" },
      { en: "Chef Portfolio", ar: "معرض طاهي" },
      { en: "Craftsman", ar: "حرفي مبدع" },
      { en: "Artist Gallery", ar: "معرض فنان" },
    ],
    descriptions: [
      { en: "Stunning creative portfolio", ar: "معرض أعمال إبداعي مذهل" },
      { en: "Clean minimal portfolio", ar: "معرض أعمال بسيط ونظيف" },
      { en: "Photography portfolio", ar: "معرض تصوير فوتوغرافي" },
      { en: "Design studio portfolio", ar: "معرض استوديو تصميم" },
      { en: "Filmmaker showreel", ar: "معرض صانع أفلام" },
      { en: "Illustration portfolio", ar: "معرض رسومات وإيضاحات" },
      { en: "Architecture portfolio", ar: "معرض أعمال معمارية" },
      { en: "Fashion designer portfolio", ar: "معرض مصمم أزياء" },
      { en: "Music artist portfolio", ar: "معرض فنان موسيقي" },
      { en: "Freelancer portfolio", ar: "معرض أعمال مستقل" },
      { en: "Writer and author portfolio", ar: "معرض كاتب ومؤلف" },
      { en: "UX/UI designer portfolio", ar: "معرض مصمم واجهات" },
      { en: "Brand identity showcase", ar: "عرض هوية علامة تجارية" },
      { en: "Motion design portfolio", ar: "معرض تصميم حركة" },
      { en: "3D art and modeling", ar: "فن ونمذجة ثلاثية الأبعاد" },
      { en: "Interior design portfolio", ar: "معرض تصميم داخلي" },
      { en: "Arabic calligraphy portfolio", ar: "معرض خط عربي" },
      { en: "Chef and culinary portfolio", ar: "معرض طاهي وفنون الطهي" },
      { en: "Handcraft showcase", ar: "عرض أعمال حرفية يدوية" },
      { en: "Fine art gallery", ar: "معرض فنون جميلة" },
    ],
    heroTitles: [
      "سارة أحمد", "معرض الأعمال", "عدسة إبداعية",
      "استوديو التصميم", "سينما الإبداع", "فن الرسم",
      "عمارة وإبداع", "تصاميم مميزة", "أنغام وألحان",
      "أعمالي المميزة", "كلمات وإبداع", "تصميم بلا حدود",
      "هوية فريدة", "حركة وإبداع", "أبعاد ثلاثية",
      "فضاءات داخلية", "جمال الخط العربي", "فن الطهي",
      "حرف وإبداع", "لوحات فنية",
    ],
    heroSubtitles: [
      "مديرة إبداعية متخصصة في التصميم الجرافيكي والهوية البصرية",
      "معرض أعمال يجمع أفضل المشاريع والتصاميم الإبداعية",
      "تصوير فوتوغرافي احترافي يروي القصص بالصور والضوء",
      "استوديو تصميم متكامل يقدم حلول إبداعية مبتكرة",
      "صناعة أفلام وثائقية وإعلانية بأحدث التقنيات",
      "رسومات وإيضاحات فنية تجمع بين الإبداع والاحتراف",
      "تصاميم معمارية تجمع بين الجمال والوظيفة والاستدامة",
      "تصاميم أزياء عصرية تجمع بين التراث العربي والحداثة",
      "موسيقى أصيلة تمزج بين الشرق والغرب بإبداع",
      "خبرة في التصميم والتطوير والتسويق الرقمي",
      "كتابة إبداعية ومحتوى تسويقي يجذب ويقنع",
      "تصميم واجهات مستخدم بديهية وتجارب رقمية مميزة",
      "بناء هويات بصرية قوية تميز علامتك التجارية",
      "تصميم حركة وأنيميشن يبث الحياة في الأفكار",
      "نمذجة ثلاثية الأبعاد واقعية لمختلف المشاريع",
      "تصميم فضاءات داخلية أنيقة تعكس شخصيتك",
      "فن الخط العربي بين الأصالة والمعاصرة",
      "وصفات مبتكرة تجمع بين النكهات العربية والعالمية",
      "أعمال حرفية يدوية مصنوعة بعناية وإتقان",
      "لوحات فنية تعبر عن الروح والإبداع العربي",
    ],
    ctaTexts: [
      "شاهد أعمالي", "تواصل معي", "اطلب جلسة تصوير", "ابدأ مشروعك",
      "شاهد الأفلام", "اطلب رسمة", "شاهد المشاريع", "صمم أزياءك",
      "استمع الآن", "وظفني", "اقرأ المزيد", "ابدأ تصميمك",
      "ابنِ هويتك", "شاهد الحركة", "شاهد الأعمال", "صمم فضاءك",
      "اطلب خطك", "احجز طاهيك", "اطلب قطعتك", "شاهد اللوحات",
    ],
    featureNames: [
      ["تصميم جرافيك", "هوية بصرية", "تجربة مستخدم"],
      ["تصوير", "مونتاج", "إخراج"],
      ["إبداع", "احتراف", "شغف"],
    ],
  },
  landing: {
    names: [
      { en: "Landing Page Pro", ar: "صفحة هبوط احترافية" },
      { en: "SaaS Landing", ar: "صفحة هبوط SaaS" },
      { en: "App Launch", ar: "إطلاق تطبيق" },
      { en: "Product Hunt", ar: "إطلاق منتج" },
      { en: "Coming Soon", ar: "قريباً" },
      { en: "Waitlist", ar: "قائمة الانتظار" },
      { en: "Course Launch", ar: "إطلاق دورة" },
      { en: "Ebook Landing", ar: "صفحة كتاب إلكتروني" },
      { en: "Webinar Page", ar: "صفحة ويبينار" },
      { en: "Newsletter", ar: "نشرة إخبارية" },
      { en: "Crowdfunding", ar: "تمويل جماعي" },
      { en: "Podcast Page", ar: "صفحة بودكاست" },
      { en: "Beta Access", ar: "وصول تجريبي" },
      { en: "Conference", ar: "مؤتمر" },
      { en: "Workshop", ar: "ورشة عمل" },
      { en: "Membership", ar: "عضوية حصرية" },
      { en: "Agency Pitch", ar: "عرض وكالة" },
      { en: "Case Study", ar: "دراسة حالة" },
      { en: "Lead Magnet", ar: "جذب العملاء" },
      { en: "SaaS Pricing", ar: "تسعير SaaS" },
    ],
    descriptions: [
      { en: "High-converting landing page", ar: "صفحة هبوط عالية التحويل" },
      { en: "Modern SaaS landing page", ar: "صفحة هبوط SaaS حديثة" },
      { en: "Mobile app launch page", ar: "صفحة إطلاق تطبيق جوال" },
      { en: "Product launch landing page", ar: "صفحة إطلاق منتج جديد" },
      { en: "Coming soon teaser page", ar: "صفحة تشويقية قريباً" },
      { en: "Waitlist signup page", ar: "صفحة تسجيل قائمة انتظار" },
      { en: "Online course launch page", ar: "صفحة إطلاق دورة أونلاين" },
      { en: "Ebook download page", ar: "صفحة تحميل كتاب إلكتروني" },
      { en: "Webinar registration page", ar: "صفحة تسجيل ويبينار" },
      { en: "Newsletter signup page", ar: "صفحة اشتراك نشرة إخبارية" },
      { en: "Crowdfunding campaign page", ar: "صفحة حملة تمويل جماعي" },
      { en: "Podcast landing page", ar: "صفحة هبوط بودكاست" },
      { en: "Beta access signup page", ar: "صفحة تسجيل وصول تجريبي" },
      { en: "Conference registration", ar: "صفحة تسجيل مؤتمر" },
      { en: "Workshop registration page", ar: "صفحة تسجيل ورشة عمل" },
      { en: "Membership landing page", ar: "صفحة عضوية حصرية" },
      { en: "Agency pitch page", ar: "صفحة عرض خدمات وكالة" },
      { en: "Case study showcase", ar: "عرض دراسة حالة" },
      { en: "Lead magnet landing page", ar: "صفحة جذب عملاء محتملين" },
      { en: "SaaS pricing page template", ar: "قالب صفحة تسعير SaaS" },
    ],
    heroTitles: [
      "سرّع نموك", "ابنِ أسرع", "تطبيقك الجديد",
      "منتج يغير اللعبة", "شيء مذهل قادم", "كن أول من يعرف",
      "تعلّم مع الخبراء", "دليلك الشامل", "ويبينار مجاني",
      "ابقَ على اطلاع", "ادعم الفكرة", "استمع وتعلم",
      "جرب قبل الجميع", "المؤتمر الأكبر", "تعلّم بالممارسة",
      "انضم للنخبة", "نصنع المستحيل", "نتائج حقيقية",
      "احصل عليه مجاناً", "خطط تناسب الجميع",
    ],
    heroSubtitles: [
      "المنصة المتكاملة لتسريع نمو أعمالك وتحقيق أهدافك",
      "ابنِ وانشر وطوّر تطبيقاتك بثقة وسرعة فائقة",
      "تطبيق ذكي يجعل حياتك أسهل وأكثر إنتاجية",
      "منتج مبتكر سيغير طريقة عملك بالكامل",
      "نعمل على شيء مذهل سيغير قواعد اللعبة",
      "سجل الآن لتكون أول من يحصل على الوصول",
      "دورة تدريبية شاملة من أفضل الخبراء في المجال",
      "كل ما تحتاج معرفته في كتاب إلكتروني واحد",
      "ويبينار مجاني يكشف أسرار النجاح في عالم الأعمال",
      "أخبار وتحديثات حصرية تصلك أسبوعياً",
      "ساعدنا في تحويل هذه الفكرة إلى واقع ملموس",
      "بودكاست أسبوعي يناقش أحدث الاتجاهات والأفكار",
      "احصل على وصول مبكر حصري قبل الإطلاق الرسمي",
      "المؤتمر الأكبر في المنطقة لرواد الأعمال والمبدعين",
      "ورشة عمل تفاعلية تعلمك المهارات الأساسية",
      "انضم لمجتمع حصري من المحترفين والخبراء",
      "وكالة رقمية تصنع علامات تجارية لا تُنسى",
      "كيف ساعدنا عملاءنا في تحقيق نتائج مذهلة",
      "احصل على دليلك المجاني الآن وابدأ رحلة النجاح",
      "خطط أسعار مرنة تناسب جميع أحجام الأعمال",
    ],
    ctaTexts: [
      "ابدأ تجربتك المجانية", "ابدأ البناء", "حمّل التطبيق", "اطلب مبكراً",
      "أبقني على اطلاع", "انضم للقائمة", "سجل في الدورة", "حمّل الكتاب",
      "سجل مجاناً", "اشترك الآن", "ادعم المشروع", "استمع الآن",
      "احصل على الوصول", "سجل حضورك", "احجز مقعدك", "انضم الآن",
      "تواصل معنا", "اقرأ الدراسة", "حمّل مجاناً", "اختر خطتك",
    ],
    featureNames: [
      ["سرعة فائقة", "أمان عالي", "دعم مستمر"],
      ["سهولة الاستخدام", "تكامل شامل", "تحديثات مجانية"],
      ["تجربة مجانية", "بدون التزام", "إلغاء في أي وقت"],
    ],
  },
  ecommerce: {
    names: [
      { en: "E-Commerce Store", ar: "متجر إلكتروني" },
      { en: "Fashion Boutique", ar: "بوتيك أزياء" },
      { en: "Perfume Collection", ar: "مجموعة عطور" },
      { en: "Jewelry Store", ar: "متجر مجوهرات" },
      { en: "Electronics Shop", ar: "متجر إلكترونيات" },
      { en: "Furniture Store", ar: "متجر أثاث" },
      { en: "Kids Store", ar: "متجر أطفال" },
      { en: "Sports Store", ar: "متجر رياضي" },
      { en: "Beauty Store", ar: "متجر تجميل" },
      { en: "Book Store", ar: "مكتبة" },
      { en: "Watch Store", ar: "متجر ساعات" },
      { en: "Shoe Store", ar: "متجر أحذية" },
      { en: "Bag Store", ar: "متجر حقائب" },
      { en: "Home Decor", ar: "ديكور منزلي" },
      { en: "Organic Store", ar: "متجر عضوي" },
      { en: "Gift Shop", ar: "متجر هدايا" },
      { en: "Pet Store", ar: "متجر حيوانات" },
      { en: "Art Store", ar: "متجر فنون" },
      { en: "Music Store", ar: "متجر موسيقى" },
      { en: "Gadget Store", ar: "متجر أجهزة" },
    ],
    descriptions: [
      { en: "Professional e-commerce template", ar: "قالب متجر إلكتروني احترافي" },
      { en: "Elegant fashion boutique", ar: "بوتيك أزياء أنيق" },
      { en: "Luxury perfume collection", ar: "مجموعة عطور فاخرة" },
      { en: "Jewelry store template", ar: "قالب متجر مجوهرات" },
      { en: "Electronics shop template", ar: "قالب متجر إلكترونيات" },
      { en: "Furniture store template", ar: "قالب متجر أثاث" },
      { en: "Kids store template", ar: "قالب متجر أطفال" },
      { en: "Sports store template", ar: "قالب متجر رياضي" },
      { en: "Beauty and cosmetics store", ar: "قالب متجر تجميل ومستحضرات" },
      { en: "Online bookstore template", ar: "قالب مكتبة إلكترونية" },
      { en: "Luxury watch store", ar: "قالب متجر ساعات فاخرة" },
      { en: "Shoe store template", ar: "قالب متجر أحذية" },
      { en: "Bag store template", ar: "قالب متجر حقائب" },
      { en: "Home decor store template", ar: "قالب متجر ديكور منزلي" },
      { en: "Organic products store", ar: "قالب متجر منتجات عضوية" },
      { en: "Gift shop template", ar: "قالب متجر هدايا" },
      { en: "Pet store template", ar: "قالب متجر حيوانات أليفة" },
      { en: "Art and prints store", ar: "قالب متجر فنون ومطبوعات" },
      { en: "Music instruments store", ar: "قالب متجر آلات موسيقية" },
      { en: "Gadget store template", ar: "قالب متجر أجهزة ذكية" },
    ],
    heroTitles: [
      "اكتشف أناقتك", "ميزون الأزياء", "عطور فاخرة",
      "مجوهرات ثمينة", "أحدث التقنيات", "أثاث عصري",
      "عالم الصغار", "معدات الأبطال", "جمالك يبدأ هنا",
      "عالم المعرفة", "ساعات فاخرة", "خطوات مميزة",
      "حقائب فاخرة", "ديكور يلهمك", "طبيعي ١٠٠٪",
      "هدية مثالية", "رفيقك الوفي", "فن وإبداع",
      "أنغام الموسيقى", "أجهزة المستقبل",
    ],
    heroSubtitles: [
      "تشكيلة واسعة من أحدث الأزياء العصرية بأسعار مميزة",
      "أزياء راقية تجمع بين الأصالة العربية والأناقة العالمية",
      "عطور فاخرة من أرقى العلامات التجارية العالمية",
      "مجوهرات ثمينة مصنوعة بعناية فائقة من أنقى المعادن",
      "أحدث الأجهزة الإلكترونية بأفضل الأسعار وضمان شامل",
      "أثاث عصري وأنيق يحول منزلك إلى واحة من الراحة",
      "كل ما يحتاجه طفلك من ملابس وألعاب ومستلزمات",
      "معدات رياضية احترافية لكل أنواع الرياضات والتمارين",
      "مستحضرات تجميل أصلية من أشهر العلامات التجارية",
      "آلاف العناوين من الكتب العربية والمترجمة بأسعار مميزة",
      "ساعات فاخرة أصلية من أرقى الماركات العالمية",
      "أحذية مميزة لكل المناسبات بتصاميم عصرية وأنيقة",
      "حقائب فاخرة من أشهر بيوت الأزياء العالمية",
      "قطع ديكور فريدة تضيف لمسة جمال لكل ركن",
      "منتجات عضوية طبيعية ١٠٠٪ لحياة صحية أفضل",
      "أفكار هدايا مميزة لكل المناسبات والأحباء",
      "كل ما يحتاجه رفيقك الأليف من طعام ومستلزمات",
      "لوحات فنية ومطبوعات حصرية تزين جدرانك",
      "آلات موسيقية أصلية من أفضل العلامات التجارية",
      "أحدث الأجهزة الذكية والإكسسوارات التقنية",
    ],
    ctaTexts: [
      "تسوق الآن", "اكتشف المجموعة", "تسوق العطور", "شاهد المجموعة",
      "تسوق الأجهزة", "تصفح الأثاث", "تسوق للصغار", "تسوق المعدات",
      "تسوق الجمال", "تصفح الكتب", "شاهد الساعات", "تسوق الأحذية",
      "تسوق الحقائب", "تصفح الديكور", "تسوق عضوي", "اختر هديتك",
      "تسوق لرفيقك", "شاهد اللوحات", "تسوق الآلات", "تسوق الأجهزة",
    ],
    featureNames: [
      ["توصيل سريع", "دفع آمن", "إرجاع مجاني"],
      ["منتجات أصلية", "ضمان الجودة", "خدمة عملاء"],
      ["عروض حصرية", "شحن مجاني", "تقسيط ميسر"],
    ],
  },
};

function generateTemplateHtml(
  category: string,
  index: number,
  title: string,
  subtitle: string,
  cta: string,
  features: string[],
  imageId: string,
  gradient: string,
  accent: string,
): string {
  const imgUrl = `https://images.unsplash.com/${imageId}?w=1200&h=600&fit=crop`;
  const thumbUrl = `https://images.unsplash.com/${imageId}?w=400&h=400&fit=crop`;

  return `<div style="font-family: 'Cairo', 'Tajawal', sans-serif; max-width: 1200px; margin: 0 auto; direction: rtl;">
<header style="padding: 5rem 2rem; text-align: center; background: ${gradient}; color: white; border-radius: 1rem; position: relative; overflow: hidden;">
<div style="position: absolute; inset: 0; background: url('${imgUrl}') center/cover; opacity: 0.2;"></div>
<div style="position: relative;">
<h1 style="font-size: 3rem; margin-bottom: 1rem; font-weight: 800; font-family: 'Cairo', sans-serif;">${title}</h1>
<p style="font-size: 1.2rem; opacity: 0.9; max-width: 600px; margin: 0 auto 2rem; font-family: 'Tajawal', sans-serif;">${subtitle}</p>
<a style="display: inline-block; padding: 0.875rem 2.5rem; background: ${accent}; color: white; border-radius: 2rem; font-weight: 700; text-decoration: none; font-family: 'Cairo', sans-serif; font-size: 1.05rem;">${cta}</a>
</div>
</header>
<section style="padding: 3rem 2rem; display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; direction: rtl;">
${features.map(f => `<div style="padding: 2rem; background: #f8fafc; border-radius: 1rem; text-align: center; border-top: 3px solid ${accent};"><h3 style="color: #0f172a; margin-bottom: 0.5rem; font-family: 'Cairo', sans-serif; font-weight: 700;">${f}</h3><p style="color: #64748b; font-family: 'Tajawal', sans-serif;">خدمة متميزة</p></div>`).join("")}
</section>
</div>`;
}

export async function seedDatabase() {
  const existing = await db.select().from(templates);
  if (existing.length > 0) return;

  const allTemplates: any[] = [];
  const categories = Object.keys(categoryConfigs);

  for (const category of categories) {
    const config = categoryConfigs[category];
    const images = heroImages[category as keyof typeof heroImages];

    for (let i = 0; i < 20; i++) {
      const name = config.names[i];
      const desc = config.descriptions[i];
      const title = config.heroTitles[i];
      const subtitle = config.heroSubtitles[i];
      const cta = config.ctaTexts[i];
      const featureSet = config.featureNames[i % config.featureNames.length];
      const imageId = images[i % images.length];
      const gradient = gradients[i % gradients.length];
      const accent = accentColors[i % accentColors.length];
      const isPremium = i >= 5;

      const html = generateTemplateHtml(category, i, title, subtitle, cta, featureSet, imageId, gradient, accent);

      allTemplates.push({
        name: name.en,
        nameAr: name.ar,
        description: desc.en,
        descriptionAr: desc.ar,
        category,
        thumbnail: `https://images.unsplash.com/${imageId}?w=400&h=300&fit=crop`,
        isPremium,
        previewHtml: html,
        previewCss: "* { margin: 0; padding: 0; box-sizing: border-box; }",
      });
    }
  }

  await db.insert(templates).values(allTemplates);
  console.log(`Database seeded with ${allTemplates.length} templates`);
}
